### ISSUE TITLE
kissanime cloudflare protection 

### ISSUE THREAD

**Issue by persian12** [HIGHWAY99/repository.thehighway#7]
today i try to user the kissanime repo in kodi 14.2 and when i hit on anime list latest update a tab saying kissanime cloudflare protection is displayed next to the loading search ?

**Comment by swavkulinski** [comment]
same thing on both 0.9.2 and 0.9.3 plugins running on Kodi 14.2 Git:7cc53a9

**Comment by HIGHWAY99** [comment]
0.9.4 should do away with the need of a 2nd click to get pages to come up, also takes care of the new link redirector issue that has CF protection up on it atm.

Usually when there's CLOUDFLARE protection up, you just gotta be patient people!  We never know what changes they'll have made for that from one time to the next, so you gotta learn to be patient.  It's obvious to most that when that's up, cURL'ing urls aint possible, due to the need of cookies and javascript.  There's a work-a-round in place but it doesn't ALWAYS work every time, and with continual changes, it'll sometimes stop working, so when that happens, your stuck waiting until their troubles are OVER.  It's not nice to to bash on their site anyways while their busy trying to deal with troubles, problems or being under attack(s).  So play nice people.
